openapi: 3.0.0
info:
  title: Kudima API
  description: API para o aplicativo educacional Kudima
  version: 1.0.0

servers:
  - url: /api
    description: API Base URL

tags:
  - name: Usuários
    description: Operações relacionadas a usuários
  - name: Aulas
    description: Operações relacionadas a aulas
  - name: Provas
    description: Operações relacionadas a provas

paths:
  /usuarios:
    get:
      tags:
        - Usuários
      summary: Lista todos os usuários
      description: Retorna uma lista com todos os usuários cadastrados
      responses:
        '200':
          description: Lista de usuários obtida com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
        '500':
          description: Erro interno do servidor
    
    post:
      tags:
        - Usuários
      summary: Cria um novo usuário
      description: Cria um novo usuário no sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovoUsuario'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '400':
          description: Dados inválidos

  /usuarios/{id}:
    get:
      tags:
        - Usuários
      summary: Obtém um usuário específico
      description: Retorna os dados de um usuário pelo seu ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuário obtido com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: Usuário não encontrado
        '500':
          description: Erro interno do servidor
    
    put:
      tags:
        - Usuários
      summary: Atualiza um usuário
      description: Atualiza os dados de um usuário existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovoUsuario'
      responses:
        '200':
          description: Usuário atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: Usuário não encontrado
        '400':
          description: Dados inválidos
    
    delete:
      tags:
        - Usuários
      summary: Exclui um usuário
      description: Remove um usuário pelo seu ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuário excluído com sucesso
        '404':
          description: Usuário não encontrado
        '500':
          description: Erro interno do servidor

  /usuarios/progresso:
    post:
      tags:
        - Usuários
      summary: Atualiza o progresso do usuário
      description: Atualiza o progresso do usuário em aulas ou provas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: ID do usuário
                aulaId:
                  type: string
                  description: ID da aula concluída
                provaId:
                  type: string
                  description: ID da prova realizada
              required:
                - userId
      responses:
        '200':
          description: Progresso atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '400':
          description: Dados inválidos
        '404':
          description: Usuário não encontrado

  /aulas:
    get:
      tags:
        - Aulas
      summary: Lista todas as aulas
      description: Retorna uma lista com todas as aulas disponíveis
      parameters:
        - name: categoria
          in: query
          schema:
            type: string
          description: Filtrar por categoria
        - name: nivel
          in: query
          schema:
            type: string
            enum: [iniciante, intermediário, avançado]
          description: Filtrar por nível
      responses:
        '200':
          description: Lista de aulas obtida com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aula'
        '500':
          description: Erro interno do servidor
    
    post:
      tags:
        - Aulas
      summary: Cria uma nova aula
      description: Adiciona uma nova aula ao sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovaAula'
      responses:
        '201':
          description: Aula criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aula'
        '400':
          description: Dados inválidos

  /aulas/buscar:
    get:
      tags:
        - Aulas
      summary: Busca aulas por termo
      description: Procura aulas que contenham o termo de busca
      parameters:
        - name: termo
          in: query
          required: true
          schema:
            type: string
          description: Termo para busca
      responses:
        '200':
          description: Resultados da busca
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aula'
        '400':
          description: Termo de busca não fornecido
        '500':
          description: Erro interno do servidor

  /aulas/{id}:
    get:
      tags:
        - Aulas
      summary: Obtém uma aula específica
      description: Retorna os dados de uma aula pelo seu ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Aula obtida com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aula'
        '404':
          description: Aula não encontrada
        '500':
          description: Erro interno do servidor
    
    put:
      tags:
        - Aulas
      summary: Atualiza uma aula
      description: Atualiza os dados de uma aula existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovaAula'
      responses:
        '200':
          description: Aula atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aula'
        '404':
          description: Aula não encontrada
        '400':
          description: Dados inválidos
    
    delete:
      tags:
        - Aulas
      summary: Exclui uma aula
      description: Remove uma aula pelo seu ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Aula excluída com sucesso
        '404':
          description: Aula não encontrada
        '500':
          description: Erro interno do servidor

  /provas:
    get:
      tags:
        - Provas
      summary: Lista todas as provas
      description: Retorna uma lista com todas as provas disponíveis
      parameters:
        - name: categoria
          in: query
          schema:
            type: string
          description: Filtrar por categoria
        - name: nivel
          in: query
          schema:
            type: string
            enum: [iniciante, intermediário, avançado]
          description: Filtrar por nível
      responses:
        '200':
          description: Lista de provas obtida com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prova'
        '500':
          description: Erro interno do servidor
    
    post:
      tags:
        - Provas
      summary: Cria uma nova prova
      description: Adiciona uma nova prova ao sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovaProva'
      responses:
        '201':
          description: Prova criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prova'
        '400':
          description: Dados inválidos

  /provas/{id}:
    get:
      tags:
        - Provas
      summary: Obtém uma prova específica
      description: Retorna os dados de uma prova pelo seu ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Prova obtida com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prova'
        '404':
          description: Prova não encontrada
        '500':
          description: Erro interno do servidor
    
    put:
      tags:
        - Provas
      summary: Atualiza uma prova
      description: Atualiza os dados de uma prova existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovaProva'
      responses:
        '200':
          description: Prova atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prova'
        '404':
          description: Prova não encontrada
        '400':
          description: Dados inválidos
    
    delete:
      tags:
        - Provas
      summary: Exclui uma prova
      description: Remove uma prova pelo seu ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Prova excluída com sucesso
        '404':
          description: Prova não encontrada
        '500':
          description: Erro interno do servidor

  /provas/verificar:
    post:
      tags:
        - Provas
      summary: Verifica respostas de uma prova
      description: Verifica as respostas fornecidas para uma prova
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                provaId:
                  type: string
                  description: ID da prova
                respostas:
                  type: array
                  description: Array com as respostas selecionadas
                  items:
                    type: number
              required:
                - provaId
                - respostas
      responses:
        '200':
          description: Respostas verificadas com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoProva'
        '400':
          description: Dados inválidos
        '404':
          description: Prova não encontrada
        '500':
          description: Erro interno do servidor

components:
  schemas:
    Usuario:
      type: object
      properties:
        _id:
          type: string
        nome:
          type: string
        email:
          type: string
        tipo:
          type: string
          enum: [estudante, professor, admin]
        dataCriacao:
          type: string
          format: date-time
        progresso:
          type: object
          properties:
            aulasCompletas:
              type: array
              items:
                type: string
            provasRealizadas:
              type: array
              items:
                type: string

    NovoUsuario:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
        senha:
          type: string
        tipo:
          type: string
          enum: [estudante, professor, admin]
      required:
        - nome
        - email
        - senha

    Aula:
      type: object
      properties:
        _id:
          type: string
        titulo:
          type: string
        descricao:
          type: string
        conteudo:
          type: string
        nivel:
          type: string
          enum: [iniciante, intermediário, avançado]
        categoria:
          type: string
        recursos:
          type: object
          properties:
            videos:
              type: array
              items:
                type: string
            audios:
              type: array
              items:
                type: string
            documentos:
              type: array
              items:
                type: string
        dataCriacao:
          type: string
          format: date-time

    NovaAula:
      type: object
      properties:
        titulo:
          type: string
        descricao:
          type: string
        conteudo:
          type: string
        nivel:
          type: string
          enum: [iniciante, intermediário, avançado]
        categoria:
          type: string
        recursos:
          type: object
          properties:
            videos:
              type: array
              items:
                type: string
            audios:
              type: array
              items:
                type: string
            documentos:
              type: array
              items:
                type: string
      required:
        - titulo
        - descricao
        - conteudo
        - nivel
        - categoria

    Questao:
      type: object
      properties:
        pergunta:
          type: string
        opcoes:
          type: array
          items:
            type: string
        resposta:
          type: number

    Prova:
      type: object
      properties:
        _id:
          type: string
        titulo:
          type: string
        descricao:
          type: string
        categoria:
          type: string
        nivel:
          type: string
          enum: [iniciante, intermediário, avançado]
        questoes:
          type: array
          items:
            $ref: '#/components/schemas/Questao'
        dataCriacao:
          type: string
          format: date-time

    NovaProva:
      type: object
      properties:
        titulo:
          type: string
        descricao:
          type: string
        categoria:
          type: string
        nivel:
          type: string
          enum: [iniciante, intermediário, avançado]
        questoes:
          type: array
          items:
            $ref: '#/components/schemas/Questao'
      required:
        - titulo
        - descricao
        - categoria
        - nivel
        - questoes

    ResultadoProva:
      type: object
      properties:
        acertos:
          type: number
        total:
          type: number
        percentualAcerto:
          type: number
        resultado:
          type: array
          items:
            type: object
            properties:
              questaoIndex:
                type: number
              correto:
                type: boolean
              respostaCorreta:
                type: number 